---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, ontap, bluexp, system manager' 
summary: Erfahren Sie, was es Neues bei ONTAP -Warnmeldungen gibt. 
---
= Was ist neu bei ONTAP -Warnmeldungen?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Erfahren Sie, was es Neues bei ONTAP -Warnmeldungen gibt.



== 06. Oktober 2025



=== BlueXP alerts heißen jetzt ONTAP -Warnmeldungen

BlueXP alerts wurden in ONTAP -Warnmeldungen umbenannt.

Sie können über die linke Navigationsleiste der NetApp Konsole darauf zugreifen, indem Sie *Speicher* > *Warnungen* auswählen.



=== BlueXP heißt jetzt NetApp Console

Die NetApp Console basiert auf der verbesserten und neu strukturierten BlueXP -Grundlage und ermöglicht die zentrale Verwaltung von NetApp Storage und NetApp Data Services in On-Premises- und Cloud-Umgebungen auf Unternehmensniveau. Sie liefert Einblicke in Echtzeit, schnellere Workflows und eine vereinfachte Administration mit hoher Sicherheit und Konformität.

Einzelheiten zu den Änderungen finden Sie imlink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Versionshinweise zur NetApp Konsole"] .



== 07. Oktober 2024



=== BlueXP alerts

Sie können ONTAP Cluster mit geringer Kapazität oder geringer Leistung schnell identifizieren, das Ausmaß der Verfügbarkeit einschätzen und Sicherheitsrisiken erkennen.  Sie können Warnungen zu Kapazität, Leistung, Schutz, Verfügbarkeit, Sicherheit und Konfiguration anzeigen.



=== Alarmdetails

Sie können sich die Alarmdetails genauer ansehen und Empfehlungen finden.



=== Mit ONTAP System Manager verknüpfte Clusterdetails anzeigen

Mit BlueXP alerts können Sie Warnmeldungen im Zusammenhang mit Ihrer ONTAP Speicherumgebung anzeigen und die mit ONTAP System Manager verknüpften Details genauer untersuchen.

https://docs.netapp.com/us-en/bluexp-alerts/concept-alerts.html["Erfahren Sie mehr über BlueXP alerts"] .
